In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = sns.load_dataset("tips")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
X = df.drop("tip", axis=1)
y = df["tip"]
X

     total_bill     sex smoker   day    time  size
0         16.99  Female     No   Sun  Dinner     2
1         10.34    Male     No   Sun  Dinner     3
2         21.01    Male     No   Sun  Dinner     3
3         23.68    Male     No   Sun  Dinner     2
4         24.59  Female     No   Sun  Dinner     4
..          ...     ...    ...   ...     ...   ...
239       29.03    Male     No   Sat  Dinner     3
240       27.18  Female    Yes   Sat  Dinner     2
241       22.67    Male    Yes   Sat  Dinner     2
242       17.82    Male     No   Sat  Dinner     2
243       18.78  Female     No  Thur  Dinner     2

[244 rows x 6 columns]

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()
X_train["sex"] = le1.fit_transform(X_train["sex"])
X_train["time"] = le2.fit_transform(X_train["time"])
X_train["smoker"] = le3.fit_transform(X_train["smoker"])
X_train

     total_bill  sex  smoker   day  time  size
228       13.28    1       0   Sat     0     2
208       24.27    1       1   Sat     0     2
96        27.28    1       1   Fri     0     2
167       31.71    1       0   Sun     0     4
84        15.98    1       0  Thur     1     2
..          ...  ...     ...   ...   ...   ...
106       20.49    1       1   Sat     0     2
14        14.83    0       0   Sun     0     2
92         5.75    0       1   Fri     0     2
179       34.63    1       1   Sun     0     2
102       44.30    0       1   Sat     0     3

[195 rows x 6 columns]

In [6]:
X_test["sex"] = le1.transform(X_test["sex"])
X_test["time"] = le2.transform(X_test["time"])
X_test["smoker"] = le3.transform(X_test["smoker"])
X_test.head()

     total_bill  sex  smoker   day  time  size
24        19.82    1       0   Sat     0     2
6          8.77    1       0   Sun     0     2
153       24.55    1       0   Sun     0     4
211       25.89    1       1   Sat     0     4
198       13.00    0       1  Thur     1     2

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(drop="first"), [3])], remainder="passthrough")
X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

In [9]:
from sklearn.svm import SVR
svr = SVR(kernel="rbf")
svr.fit(X_train, y_train)
y_pred = svr.predict(X_test)

from sklearn.metrics import mean_squared_error,r2_score
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)
print(rmse)
print(r2)

0.7296412174909253
0.5740891915042661